/**
 * Image generation using Gemini native API
 *
 * Uses Gemini 2.0 Flash image generation capabilities via the native
 * generativelanguage.googleapis.com endpoint.
 *
 * For generation: sends a text prompt, expects image output.
 * For editing: sends original images + editing instructions.
 */
import { storagePut } from "../storage";
import { ENV } from "./env";

export type GenerateImageOptions = {
  prompt: string;
  originalImages?: Array<{
    url?: string;
    b64Json?: string;
    mimeType?: string;
  }>;
};

export type GenerateImageResponse = {
  url?: string;
};

const GEMINI_MODEL = "gemini-2.0-flash-exp-image-generation";
const GEMINI_API_URL = `https://generativelanguage.googleapis.com/v1beta/models/${GEMINI_MODEL}:generateContent`;

export async function generateImage(options: GenerateImageOptions): Promise<GenerateImageResponse> {
  if (!ENV.geminiApiKey) {
    throw new Error("GEMINI_API_KEY is not configured");
  }

  // Build multimodal content parts
  const parts: Array<Record<string, unknown>> = [];

  // Add original images if provided (for editing use case)
  if (options.originalImages && options.originalImages.length > 0) {
    for (const img of options.originalImages) {
      if (img.b64Json) {
        parts.push({
          inlineData: {
            mimeType: img.mimeType || "image/png",
            data: img.b64Json,
          },
        });
      } else if (img.url) {
        // Download the image and convert to base64
        const imgResponse = await fetch(img.url);
        if (imgResponse.ok) {
          const buffer = Buffer.from(await imgResponse.arrayBuffer());
          parts.push({
            inlineData: {
              mimeType: img.mimeType || imgResponse.headers.get("content-type") || "image/png",
              data: buffer.toString("base64"),
            },
          });
        }
      }
    }
  }

  // Add the text prompt
  parts.push({ text: options.prompt });

  const response = await fetch(`${GEMINI_API_URL}?key=${ENV.geminiApiKey}`, {
    method: "POST",
    headers: {
      "content-type": "application/json",
    },
    body: JSON.stringify({
      contents: [{ role: "user", parts }],
      generationConfig: {
        responseModalities: ["TEXT", "IMAGE"],
      },
    }),
  });

  if (!response.ok) {
    const detail = await response.text().catch(() => "");
    throw new Error(
      `Image generation failed (${response.status} ${response.statusText})${detail ? `: ${detail}` : ""}`,
    );
  }

  const result = (await response.json()) as {
    candidates?: Array<{
      content?: {
        parts?: Array<{
          text?: string;
          inlineData?: { mimeType: string; data: string };
        }>;
      };
    }>;
  };

  // Extract image from response
  const parts2 = result.candidates?.[0]?.content?.parts ?? [];
  for (const part of parts2) {
    if (part.inlineData?.data) {
      const buffer = Buffer.from(part.inlineData.data, "base64");
      const ext = part.inlineData.mimeType.split("/")[1] || "png";
      const { url } = await storagePut(
        `generated/${Date.now()}.${ext}`,
        buffer,
        part.inlineData.mimeType,
      );
      return { url };
    }
  }

  throw new Error("No image was generated by the model");
}
